apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: bettertodo
resources:
  - service-account.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - svc.yaml
  - secret.yaml
  - svc-headless.yaml