apiVersion: v1
kind: Service
metadata:
  name: postgres-db-postgresql
  labels:
    app: postgresql
    release: "postgres-db"
    app.kubernetes.io/part-of: vaccine-solution
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: postgresql
    release: "postgres-db"
    role: master
